# Generated by Django 3.1 on 2020-10-28 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('book_publish_date', models.CharField(max_length=20, null=True)),
                ('categories', models.CharField(max_length=200, null=True)),
                ('average_rating', models.CharField(max_length=5, null=True)),
                ('ratings_count', models.CharField(max_length=5, null=True)),
                ('thumbnail', models.TextField()),
                ('authors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publisheddate.authors')),
            ],
        ),
    ]
